// Clickbait and rage-bait phrasing commonly used to provoke outrage or curiosity.
// These expressions are intentionally broad so the detector can score variations,
// not just exact headline matches.
export const RAGE_BAIT_PATTERNS = [
  /you\s+won'?t\s+believe/i,
  /you\s+won'?t\s+believe\s+what\s+happened/i,
  /you\s+won'?t\s+believe\s+what\s+they\s+did/i,
  /shocking\s+truth/i,
  /the\s+shocking\s+truth/i,
  /they\s+don'?t\s+want\s+you\s+to\s+know/i,
  /this\s+will\s+blow\s+your\s+mind/i,
  /what\s+happens\s+next\s+will\s+shock\s+you/i,
  /what\s+happened\s+next\s+was\s+shocking/i,
  /the\s+result\s+will\s+shock\s+you/i,
  /the\s+ending\s+will\s+leave\s+you\s+speechless/i,
  /you\s+need\s+to\s+see\s+this/i,
  /you\s+have\s+to\s+see\s+this/i,
  /the\s+internet\s+is\s+losing\s+its\s+mind/i,
  /people\s+are\s+furious/i,
  /everyone\s+is\s+talking\s+about\s+this/i,
  /everyone\s+is\s+outraged/i,
  /critics\s+are\s+melting\s+down/i,
  /absolute\s+chaos/i,
  /pure\s+chaos/i,
  /this\s+changes\s+everything/i,
  /nothing\s+will\s+ever\s+be\s+the\s+same/i,
  /the\s+truth\s+they\s+hid/i,
  /the\s+secret\s+they\s+never\s+wanted\s+revealed/i,
  /mainstream\s+media\s+won'?t\s+show\s+you/i,
  /the\s+media\s+is\s+silent/i,
  /watch\s+before\s+it'?s\s+deleted/i,
  /before\s+they\s+take\s+this\s+down/i,
  /banned\s+video/i,
  /censored\s+by\s+the\s+media/i,
  /elites\s+don'?t\s+want\s+you\s+to\s+see\s+this/i,
  /they\s+tried\s+to\s+hide\s+this/i,
  /this\s+one\s+trick/i,
  /doctors\s+hate\s+this/i,
  /experts\s+are\s+stunned/i,
  /scientists\s+can'?t\s+explain/i,
  /jaw[-\s]?dropping/i,
  /mind[-\s]?blowing/i,
  /stunning\s+revelation/i,
  /bombshell\s+report/i,
  /devastating\s+expose/i,
  /caught\s+on\s+camera/i,
  /you\s+won'?t\s+last\s+to\s+the\s+end/i,
  /wait\s+until\s+you\s+see/i,
  /what\s+they\s+found\s+is\s+terrifying/i,
  /the\s+real\s+story\s+finally\s+revealed/i,
  /truth\s+finally\s+comes\s+out/i,
  /gone\s+wrong/i,
  /gone\s+too\s+far/i,
  /this\s+is\s+insane/i,
];

// High-intensity emotional vocabulary often used to amplify fear, anger,
// urgency, or disgust beyond the underlying facts.
export const EMOTIONAL_MANIPULATION_WORDS = [
  "outrage",
  "outraged",
  "scandal",
  "bombshell",
  "exposed",
  "shocking",
  "devastating",
  "horrifying",
  "terrifying",
  "furious",
  "rage",
  "rage-bait",
  "explosive",
  "stunning",
  "unbelievable",
  "disgusting",
  "chaos",
  "panic",
  "fear",
  "fearful",
  "nightmare",
  "catastrophe",
  "catastrophic",
  "sinister",
  "corrupt",
  "evil",
  "disaster",
  "meltdown",
  "humiliating",
  "violent",
  "brutal",
  "shameful",
  "alarming",
  "appalling",
  "heartbreaking",
  "sickening",
  "disturbing",
  "scary",
  "menacing",
  "dangerous",
  "threatening",
  "toxic",
  "crushing",
  "grim",
  "dreadful",
  "harrowing",
  "hysterical",
  "desperate",
  "frantic",
  "massive",
  "urgent",
  "emergency",
  "crisis",
  "fraud",
  "cover-up",
  "coverup",
  "betrayal",
  "traitor",
  "collapse",
  "ruined",
  "destroyed",
  "wrecked",
  "abuse",
  "manipulated",
  "suppressed",
  "censored",
  "exploitation",
  "hunted",
  "victim",
  "weaponized",
];

// Structural signals that can suggest AI-generated prose. These are not direct
// verdicts; they are heuristics a detector can score against paragraph- or
// document-level writing patterns.
export const AI_PATTERNS = {
  repetitiveSentenceStarters: [
    /^(in\s+addition|moreover|furthermore|however|therefore|overall|meanwhile)\b/im,
    /^(it\s+is\s+important\s+to\s+note|it\s+is\s+worth\s+noting|it\s+should\s+be\s+noted)\b/im,
    /^(on\s+the\s+other\s+hand|at\s+the\s+same\s+time|in\s+contrast)\b/im,
  ],
  transitionOveruse: [
    /\b(however|moreover|furthermore|therefore|thus|consequently|nevertheless|additionally|overall)\b/gi,
    /\b(in\s+conclusion|to\s+summarize|in\s+summary|all\s+things\s+considered)\b/gi,
  ],
  unnaturalPerfectGrammar: [
    /\bmeticulously\s+crafted\b/i,
    /\bseamless(?:ly)?\b/i,
    /\bwell-structured\b/i,
    /\bclear\s+and\s+concise\b/i,
    /\bdelve\s+into\b/i,
    /\bcomprehensive\s+overview\b/i,
  ],
  genericConclusions: [
    /\bin\s+conclusion[, ]/i,
    /\bultimately[, ]/i,
    /\boverall[, ]/i,
    /\bit\s+is\s+clear\s+that\b/i,
    /\bthe\s+bottom\s+line\s+is\b/i,
    /\bthis\s+highlights\s+the\s+importance\s+of\b/i,
    /\bas\s+we\s+have\s+seen\b/i,
  ],
  repetitiveFraming: [
    /\bit\s+is\s+important\s+to\s+understand\b/gi,
    /\bone\s+key\s+aspect\b/gi,
    /\banother\s+important\s+point\b/gi,
    /\bfrom\s+this\s+perspective\b/gi,
  ],
};

// Vague sourcing and weak attribution cues often found in misleading or
// unverified claims. These help identify statements that imply evidence
// without naming a concrete source.
export const UNVERIFIED_CLAIM_INDICATORS = [
  /some\s+say/i,
  /many\s+people\s+are\s+saying/i,
  /reports\s+suggest/i,
  /sources\s+claim/i,
  /it\s+is\s+being\s+said/i,
  /critics\s+say/i,
  /insiders\s+say/i,
  /people\s+are\s+saying/i,
  /it\s+is\s+rumored/i,
  /rumor\s+has\s+it/i,
  /allegedly/i,
  /reportedly/i,
  /according\s+to\s+sources/i,
  /according\s+to\s+insiders/i,
  /anonymous\s+sources/i,
  /unnamed\s+sources/i,
  /observers\s+believe/i,
  /experts\s+say/i,
  /some\s+experts\s+believe/i,
  /many\s+believe/i,
  /there\s+is\s+growing\s+belief/i,
  /it\s+appears\s+that/i,
  /it\s+seems\s+that/i,
  /it\s+is\s+widely\s+believed/i,
  /questions\s+are\s+being\s+asked/i,
  /concerns\s+have\s+been\s+raised/i,
  /evidence\s+suggests/i,
  /sources\s+close\s+to\s+the\s+matter/i,
  /those\s+familiar\s+with\s+the\s+situation/i,
  /without\s+providing\s+evidence/i,
  /\bthey\s+say\b/i,
  /\bword\s+is\b/i,
  /\bclaims\s+have\s+surfaced\b/i,
  /\bthere\s+are\s+claims\s+that\b/i,
  /\bit\s+has\s+been\s+claimed\b/i,
];
